### ISSUE TITLE
adjust guidence wrt this being the recommended benchmarking solution?

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/benchmark_harness#73]
Hi - I'm very excited to see activity in this repo again, including discussion about possible improvements to the benchmarking technique - https://github.com/dart-lang/benchmark_harness/pull/38#issuecomment-1116055039.

I think there's an open question about whether this is a general purpose benchmarking package or one that's now effectively just tailored for supporting internal dart benchmarking. I think either is ok, but we should communicate which to users.

Right now, in the readme we have `The Dart project benchmark harness is the recommended starting point when building a benchmark for Dart.`, and in the pubspec we have: `The official Dart project benchmark harness`.

I'd like to choose one, and adjust our messaging to match; @sortie - thoughts?

**Comment by sortie** [comment]
Right now, it's first and foremost the solution that powers our own benchmarks, but it does work for other people too and we'd like for it to be nicer for everypne. We have some key compatibility constraints due to our own benchmarking that needs to be really carefully managed. This package needs work done to remove some legacy problems (such as results being off by 10x) and turning it into an overall nicer benchmarking solution for us, which also benefits everyone else.

I'm sort of okay with this package having some aspirational messaging (as it always has had) while we improve it over time. The biggest issue from a customer POV is that we're a little inflexible with contributions due to our own internal compatibility constraints that they wouldn't quite know about.

So overall, the state of this package is not that great, but it's something we'll want to improve.

**Comment by devoncarew** [comment]
> I'm sort of okay with this package having some aspirational messaging (as it always has had) while we improve it over time. The biggest issue from a customer POV is that we're a little inflexible with contributions due to our own internal compatibility constraints that they wouldn't quite know about.

If we intend to get to it being for general-purpose use, sgtm (if however we thought we could never make it general purpose, due, due to internal constraints, then we should just fork the package and keep a specialized one for internal use only).

**Comment by devoncarew** [comment]
Closing as this package has seen a lot more maintenance recently.
